// <auto-generated />
using System;
using Core_Crud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core_Crud.Migrations
{
    [DbContext(typeof(Core_Crud0921Context))]
    [Migration("20190928052018_addingcustomvalidation2")]
    partial class addingcustomvalidation2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core_Crud.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(27);

                    b.HasKey("ID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Core_Crud.Models.Destination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrival_Date");

                    b.Property<decimal>("Bill")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CountryId");

                    b.Property<DateTime>("Departure_Date");

                    b.Property<string>("Destination_Name")
                        .IsRequired();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<bool>("Has_breakfast");

                    b.Property<string>("ResortPhone")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("Core_Crud.Models.Destination", b =>
                {
                    b.HasOne("Core_Crud.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
