// <auto-generated />
using System;
using Core_Crud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core_Crud.Migrations
{
    [DbContext(typeof(Core_CrudContext))]
    [Migration("20190914063641_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core_Crud.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DestinationID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("DestinationID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Core_Crud.Models.Destination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrival_Date");

                    b.Property<decimal>("Bill")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Departure_Date");

                    b.Property<string>("Destination_Name");

                    b.Property<bool>("Has_breakfast");

                    b.HasKey("ID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("Core_Crud.Models.Country", b =>
                {
                    b.HasOne("Core_Crud.Models.Destination")
                        .WithMany("Countries")
                        .HasForeignKey("DestinationID");
                });
#pragma warning restore 612, 618
        }
    }
}
